from .register_viewset import register_user
from .user_viewset import UserViewSet
from .team_viewset import TeamViewSet
from .user_profile_viewset import UserProfileViewSet
from .pit_prompt_viewset import PitPromptViewSet
from .competition_viewset import CompetitionViewSet
from .pit_scouting_viewset import PitScoutingViewSet
from .match_viewset import MatchViewSet
from .match_data_viewset import MatchDataViewSet
from .team_match_rel_viewset import TeamMatchRelViewSet